#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tao map V4: Viet hoa khong dau tat ca class con lai co CJK.
Doc V3, ghi V4 moi. Khong xoa/ghi de map cu.
"""
from pathlib import Path
import json

BASE = Path('config/class_string_map_safe_vi_ascii_v3_all_remaining.json')
OUT = Path('config/class_string_map_safe_vi_ascii_v4_all_classes.json')

m = json.loads(BASE.read_text(encoding='utf-8'))

ADD = {
# a.class - key names
" # 键": " # key",
" * 键": " * key",
"上方向键": "Phim len",
"下方向键": "Phim xuong",
"右方向键": "Phim phai",
"右软键": "Soft phai",
"左方向键": "Phim trai",
"左软键": "Soft trai",
"数字键0": "Phim 0",
"数字键1": "Phim 1",
"数字键3": "Phim 3",
"数字键5": "Phim 5",
"数字键7": "Phim 7",
"数字键9": "Phim 9",

# aa.class - battle/system tips
"升至": "Len ",
"当前地图不能攻击": "Map nay khong the ATK",
"怒气不足": "Thieu no khi",
"技能未就绪": "Skill chua san sang",
"无敌效果结束": "Het hieu ung bat tu",
"级": "Lv",
"请按": "Bam ",
"魔法不足": "Thieu MP",

# ae.class layout marker (no display). Patch only in V4 because user requested all remaining.
"宽": "W",

# af.class - UC/payment/network text
" U点": " Ucoin",
"(发送短信：": "(Gui SMS:",
"优视科技 版权所有": "UC Mobile ban quyen",
"元": "CNY",
"对不起，您所在的地区没有开通短信付费通道，请使用U点进行支付！": "Khu vuc cua ban chua ho tro SMS. Hay dung Ucoin de thanh toan!",
"您的账号或密码错误，请重新输入。": "Sai TK/MK, nhap lai.",
"您的账户余额不足，无法完成本次支付，请用UC浏览器登录UC充值中心(pay.uc.cn)为U点账户充值。": "So du khong du. Hay dung UC Browser vao pay.uc.cn de nap Ucoin.",
"折": "giam",
"支付失败，原因：": "Tra phi loi, ly do: ",
"支付密码": "MK tra phi",
"无折扣": "Khong giam",
"条)": " tin)",
"正在初始化数据，请稍等": "Dang khoi tao du lieu, doi chut",
"正在重试联网...": "Dang ket noi lai...",
"消费金额填写不正确！": "So tien nhap sai!",
"系统错误，支付失败，U点未被扣除，请重试或更换其他支付方式！": "Loi he thong, tra phi that bai, Ucoin chua bi tru. Thu lai hoac doi cach khac!",
"网络繁忙，连接失败，本次支付不成功，请返回尝试重新支付。": "Mang ban, ket noi loi. Tra phi chua thanh cong, hay quay lai thu lai.",
"获取U点支付信息失败！": "Lay thong tin Ucoin that bai!",
"获取短信数据失败": "Lay du lieu SMS that bai",
"获取短信数据失败，请改用U点支付": "Lay SMS that bai, hay dung Ucoin",
"获取短信数据失败，请改用其他手段支付": "Lay SMS that bai, hay dung cach khac",
"错误：您输入的账号密码中含有非法字符，请检查！": "Loi: TK/MK co ky tu sai, kiem tra lai!",
"错误：支付密码中含有非法字符，请检查！": "Loi: MK tra phi co ky tu sai, kiem tra lai!",
"错误：请输入由数字组成的账号/手机号。": "Loi: Nhap TK/SDT bang so.",

# ai.class - script/task/action tips/debug
">>屏幕控制：type=": ">>Man hinh control: type=",
">>屏幕移至某点：x=": ">>Man hinh toi diem: x=",
">>执行延时：pauseTime=": ">>Delay: pauseTime=",
">>角色重生：roleID=": ">>Nhan vat hoi sinh: roleID=",
">>设置标志：roleID=": ">>Set flag: roleID=",
">>跟随对象：roleID=": ">>Theo doi tuong: roleID=",
">>镜头移至角色：roleID=": ">>Camera toi role: roleID=",
"完成: ": "Xong: ",
"强化装备": "Cuong hoa TB",
"接到: ": "Nhan: ",
"离开": "Roi di",
"绘制CG时dlgShowType选项不对": "Sai dlgShowType khi ve CG",
"获得": "Nhan",
"购买材料": "Mua vat lieu",
"跳过": "Bo qua",

# an/c/b/j/k/y debug/internal
"你看到我说明掉落物品类型出问题了:)": "Neu thay dong nay: loot type bi loi :)",
"金": "Gold",
"动画状态列表出界！baseInfo[INFO_OBJ_STATE] = ": "Anim state vuot gioi han! baseInfo[INFO_OBJ_STATE] = ",
"地图加载错误：ID=": "Loi load map: ID=",
"，不在当前地图缓存中!": ", khong trong cache map hien tai!",
"UIdata::drawSLAni:动画ID不存在1": "UIdata::drawSLAni: anim ID khong ton tai 1",
"UIdata::drawUIAni:动画ID不存在2": "UIdata::drawUIAni: anim ID khong ton tai 2",
"ui数据已经被逻辑删除": "ui data da bi logic xoa",
"文本ID不存在": "Text ID khong ton tai",
", 组name=": ", group name=",
"; 组id=": "; group id=",
">>WARNING:  任务数量已经超出组的最大容量！请程序修改！定义数量：15, 当前数量：": ">>WARNING: So NV vuot max group! Sua code! Dinh nghia:15, hien tai:",
">>WARNING:  任务组数量已经超出程序定义的量！请程序修改！定义数量：10, 当前数量：": ">>WARNING: So group NV vuot dinh nghia! Sua code! Dinh nghia:10, hien tai:",

# as.class
"保存密码？": "Luu mat khau?",
"按“确定”键返回。": "Bam OK de quay lai.",

# e.class - skills
"一闪·破": "Nhat kich Pha",
"下一级别": "Cap tiep",
"个技能点，&": " diem Skill,&",
"会心": "Chi mang",
"伤害+": "DMG+",
"伤害吸收+": "Hap thu DMG+",
"冷却": "Hoi chieu",
"升级需要": "Nang cap can",
"向天上射出冰之箭，对自身周围全部敌人造成冰冻伤害": "Ban mui ten bang len troi, gay DMG bang cho moi dich quanh minh",
"奋力的用拳对前方的地面发动猛烈震击，能将敌人挑起在半空中。": "Dam manh xuong dat phia truoc, hat dich len khong.",
"射出巨大的冰冻之箭，对一条线上的敌人造成冰冻伤害": "Ban ten bang lon, gay DMG bang cho dich tren mot duong",
"尚未习得&": "Chua hoc&",
"已经升至最高级&": "Da len cap max&",
"当前级别": "Cap hien tai",
"忍耐": "Nhan nai",
"成功防御敌人攻击，将怒气化形，以极速斩出一剑，造成普通攻击多倍以上伤害。": "DEF thanh cong, bien no khi thanh kiem chem cuc nhanh, gay DMG gap nhieu lan ATK thuong.",
"拳挑起": "Dam hat len",
"暗黑之光": "Anh sang den",
"消耗一定的怒气，&": "Ton mot so no khi,&",
"消耗魔力": "Ton MP",
"点，&": " diem,&",
"熊咆哮": "Gau gam",
"秒，&": " giay,&",
"耐性": "Khang",
"聚剑气、拳道于一体发动熊咆哮，震飞附近的所有敌人并造成大量伤害。": "Gom kiem khi va quyen dao thanh Gau Gam, day bay moi dich gan do va gay DMG lon.",
"聚集全身的剑气发动黑暗攻击，对附近大范围的敌人造成大量伤害。": "Gom kiem khi toan than tao don den, gay DMG lon len vung rong quanh do.",
"追加连击技": "Them combo skill",
"通过提升自己的力量，强化身体，增加生命最大值和基础攻击力。": "Tang suc manh de cuong hoa co the, tang HP Max va ATK co ban.",
"通过提升自己的斗气，增加吸收伤害的能力。": "Tang dau khi de tang kha nang hap thu DMG.",
"通过提升自己的精神力量，增加魔力最大值。": "Tang tinh than de tang MP Max.",
"通过提高自己的剑术，增加暴击概率。": "Tang kiem thuat de tang CRIT.",
"魔力": "MP",

# m.class - items/materials/status effects
"使主角每秒中毒10点血，持续50秒": "Lam nhan vat doc -10 HP/s trong 50s",
"使主角每秒中毒15点血，持续80秒": "Lam nhan vat doc -15 HP/s trong 80s",
"使主角每秒中毒2点血，持续15秒": "Lam nhan vat doc -2 HP/s trong 15s",
"使主角每秒中毒5点血，持续30秒": "Lam nhan vat doc -5 HP/s trong 30s",
"使主角眩晕2秒": "Lam nhan vat choang 2s",
"使主角眩晕3秒": "Lam nhan vat choang 3s",
"使主角眩晕5秒": "Lam nhan vat choang 5s",
"使主角眩晕8秒": "Lam nhan vat choang 8s",
"使用后劳拉的好感度+10。": "Dung xong do than Laura +10.",
"使用后宠物经验提升20。": "Dung xong EXP pet +20.",
"使用后怒气全满。": "Dung xong day no khi.",
"使用后技能点+1。": "Dung xong diem Skill +1.",
"使用后攻击永久+2。": "Dung xong ATK vinh vien +2.",
"使用后防御永久+1。": "Dung xong DEF vinh vien +1.",
"冰晶": "Bang tinh",
"冰晶锁": "Khoa Bang",
"刀刃": "Luoi dao",
"升级宠物所需的灵石。": "Linh thach can de nang pet.",
"原效果减10点伤害，60点时间": "Hieu ung goc giam 10 DMG, 60 time",
"原效果减11点时间": "Hieu ung goc giam 11 time",
"原效果减1点伤害，6点时间": "Hieu ung goc giam 1 DMG, 6 time",
"原效果减1点时间": "Hieu ung goc giam 1 time",
"原效果减2点时间": "Hieu ung goc giam 2 time",
"原效果减3点伤害，15点时间": "Hieu ung goc giam 3 DMG, 15 time",
"原效果减3点时间": "Hieu ung goc giam 3 time",
"原效果减4点时间": "Hieu ung goc giam 4 time",
"原效果减6点伤害，30点时间": "Hieu ung goc giam 6 DMG, 30 time",
"原效果减6点时间": "Hieu ung goc giam 6 time",
"变异蟹的钳子，非常坚硬。": "Cang cua dot bien, rat cung.",
"可还原技能点，重修技能。": "Hoan lai diem Skill de hoc lai.",
"回复HP30%。": "Hoi HP30%.",
"回复MP30%。": "Hoi MP30%.",
"宠物饲料": "Thuc an pet",
"封魔印": "An phong ma",
"幻灵界的刀刃，升级武器的材料。": "Luoi dao coi ao linh, vat lieu nang cap VK.",
"怒气石": "Da no khi",
"扎昆的心脏，充满强大的力量。": "Tim Zakun, day suc manh.",
"打造 冰晶锁 & 进入扎昆山脉所必需的任务物品，可防止酷热熔岩造成的伤害。 & 需要材料 冰晶5 刀刃4 蛇胆3 金钱1000": "Ren Khoa Bang & Vat NV can de vao nui Zakun, ngan DMG dung nham nong. & Can: Bang tinh5 Luoi dao4 Mat ran3 Gold1000",
"打造 封魔印 & 进入地下王宫所必需的任务物品。 & 需要材料  魔心50 刀刃5 蛇胆5 金钱5000": "Ren An phong ma & Vat NV can de vao cung ngam. & Can: Ma tam50 Luoi dao5 Mat ran5 Gold5000",
"打造 通天眼 & 进入夜色岛所必需的任务物品，可看穿幻灵的所有伪装。 & 需要材料  星光20 海螺壳20 青蛙心20 魔刃2 金钱2000": "Ren Thien Nhan & Vat NV can de vao Dao Dem, nhin thau moi gia trang ao linh. & Can: Anh sao20 Vo oc20 Tim ech20 Ma nhan2 Gold2000",
"技能书": "Sach Skill",
"攻击石": "Da ATK",
"星光": "Anh sao",
"极寒的冰石，具有神秘的能量。": "Da bang cuc lanh, co nang luong bi an.",
"死亡后使用可满状态复活。": "Dung sau khi chet de hoi sinh day trang thai.",
"海星星掉落的外壳，有特殊用途。": "Vo do sao bien roi, co cong dung dac biet.",
"海螺壳": "Vo oc",
"海螺的外壳，常作为打造的材料。": "Vo oc, thuong dung lam vat lieu ren.",
"灯笼怪掉落的灯芯，充满魔之力。": "Bac den quai den long roi, day ma luc.",
"炙热之心": "Tim nong",
"生命+ ": "HP+ ",
"蛇胆": "Mat ran",
"蛇胆。": "Mat ran.",
"蟹钳": "Cang cua",
"血瓶": "Binh mau",
"进入地下王宫所必需的任务物品。": "Vat NV can de vao cung ngam.",
"进入夜色岛所必需的任务物品，可看穿幻灵的所有伪装。": "Vat NV can de vao Dao Dem, nhin thau gia trang ao linh.",
"进入扎昆山脉所必需的任务物品，可防止酷热熔岩造成的伤害。": "Vat NV can de vao nui Zakun, ngan DMG dung nham nong.",
"通天眼": "Thien Nhan",
"重修书": "Sach hoc lai",
"防御石": "Da DEF",
"降低50%的速度，持续14秒": "Giam SPD 50% trong 14s",
"降低50%的速度，持续3秒": "Giam SPD 50% trong 3s",
"降低50%的速度，持续6秒": "Giam SPD 50% trong 6s",
"降低50%的速度，持续9秒": "Giam SPD 50% trong 9s",
"青蛙心": "Tim ech",
"青蛙的心，具有明目的作用。": "Tim ech, giup sang mat.",
"鬼魂的结晶。": "Ket tinh hon ma.",
"魂石": "Hon thach",
"魔兔的武器，锋利无比。": "Vu khi tho ma, cuc sac.",
"魔刃": "Ma nhan",
"魔心": "Ma tam",
"魔法+ ": "MP+ ",
"魔瓶": "Binh MP",
"魔魂石": "Da hon ma",
"鲜花": "Hoa tuoi",

# o.class five elements
"(土)": "(Tho)",
"(木)": "(Moc)",
"(水)": "(Thuy)",
"(火)": "(Hoa)",
"(金)": "(Kim)",

# q.class - paid prompts
"只需4元，即可激活正版（您需要发送2条短信完成支付，信息费2元/条，不含通信费）": "Chi 4 CNY de kich hoat ban quyen (gui 2 SMS, 2 CNY/tin, chua tinh phi mang)",
"想原地复活，并且满血满魔吗？仅需1元就可以实现你的愿望。": "Muon hoi sinh tai cho, day HP/MP? Chi 1 CNY.",
"打怪升级太慢，仅需2元，就可开启双倍经验。": "Danh quai len cap cham? Chi 2 CNY de mo EXP x2.",
"钱不够花，仅需2元，就可立即获得1000金币。": "Thieu tien? Chi 2 CNY nhan ngay 1000 Gold.",

# v/w shared leftovers
"防御": "DEF",
}

m.update(ADD)

bad = [(k, v) for k, v in m.items() if any(ord(c) > 127 for c in v)]
if bad:
    raise SystemExit('Non-ASCII values: ' + repr(bad[:20]))
OUT.write_text(json.dumps(m, ensure_ascii=False, indent=2, sort_keys=True), encoding='utf-8')
print(f'Wrote {OUT} entries={len(m)} added={len(ADD)}')
