#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tao CSV dich sct_dialogue tieng Viet khong dau, ngan de giu soft_limit."""
from pathlib import Path
import csv

SRC = Path('translations/sct_dialogue_export.csv')
OUT = Path('translations/sct_dialogue_vi_nodau.csv')

T = {
(0,0): "Nhieu nam sau, co le ai do se nho toi, hoac nho ten Ferok. Toi mong nguoi do la co ay. Chuyen 24 nam truoc, toi la mot kiem si tru gian.",
(0,1): "24 nam truoc, toi da tao nen than thoai cua Koles va co ay. Toi la ai? Kiep truoc hay nay? 24 nam sau, toi dung cau chuyen cua minh de ke ve Koles va Ailen trong ky uc. Con toi van la kiem si ay.",
(0,2): "Chuyen bat dau tu 24 nam truoc...",
(1,0): "Nui Zakun chua mo. Xem Map lon hoac NV!",
(1,1): "Cung ngam chua mo. Xem Map lon hoac NV!",
(1,2): "Dao dem chua mo. Xem Map lon hoac NV!",
(1,3): "Rung Ael chua mo. Xem Map lon hoac NV!",
(1,4): "Vung tuyet chua mo. Xem Map lon hoac NV!",
(2,0): "Co gai Jan: Ailen ra ngoai xem, bao toi doi anh o day.",
(2,1): "Ferok: Thich noi nay chu? Trong co ve vui lam.",
(2,2): "Co gai Jan: Cung duoc. Nguoi o day la, nhung khong ac y; de chiu hon ben ngoai.",
(2,3): "Phu thuy Ronin: Toi nghien cuu phep. Do o day se giup anh rat nhieu.",
(2,4): "Kunsang: Toi la tho ren Kunsang. Toi ren va cuong hoa do cho dung si. Vat lieu nhan duoc khi danh quai ngoai dong.",
(2,5): "Cau thu Fab: Cau thich bong da chu? Doan xem ta la ai?",
(2,6): "Ferok:...",
(2,7): "Cau thu Fab: Hai dong doi cua ta lac mat tren duong. Giup ta tim ho nhe?",
(2,8): "Laura: Buon ban tren dao nay that kho. Bao gio moi tim duoc viec vua y?",
(2,9): "Lang du: Chao dung si. Chao mung den xu la, noi anh se co cam giac khac thuong.",
(2,10): "Lang du: Quanh dao rat nguy, nhieu nguoi ket o day. Muon tim loi ra, hay gap truong lang Jiang.",
(2,11): "Lang du: Dao nho nhung du thu. Toi ban trang bi. Kunsang phia dong tung la tho san, gio lam tho ren.",
(2,12): "Lang du: Vao xem trang bi di.",
(2,13): "Jiang: Khuc khuc, cau moi den ha? Noi di, muon tim viec gi?",
(2,14): "Ferok: Tim viec? Lao gia, day la noi nao?",
(2,15): "Jiang: Tre tuoi, dung nong. Nghe ta noi da.",
(2,16): "Jiang: Day la lang Dung Si, ben cang cho ke lac loi. Ai den day deu la ke lac loi. Ta la truong lang Jiang, phu trach don tiep.",
(2,17): "Ferok: Ke lac loi? Nghe la day, nhung toi khong phai ke lac loi.",
(2,18): "Jiang: Cau khong lac loi, nhung dang lac duong.",
(2,19): "Jiang: Khi ke lac loi den dao Dung Si, song sot la viec dau tien. Ho deu den tim ta.",
(2,20): "Jiang: Book lo mua ban do; Kunsang tung la tho san, nay lam tho ren; phu thuy Ronin ban do dac biet; Laura ban thu cung. May ke moi den cung dang tim viec hop minh.",
(2,21): "Ferok: (Song tren dao nay con la van de, cu hoi ong ta.) Nghe cung duoc. Xin tim viec cho ca ba chung toi.",
(2,22): "Jiang: Ba nguoi? Y cau la Ailen va tieu thu Jan bung binh ma dang yeu? Cac cau moi toi dao chua lau.",
(2,23): "Ferok: Dung, la ho. Toi va Ailen gap Jan gan dao Dung Si nen dua co ay theo. Co ay hoi ngang, nhung tieu thu nao chang the; toi thay co ay cung tot.",
(2,24): "Jiang: Tre tuoi, gio viec kho tim. Dao ta con nhieu nguoi that nghiep. Nhung thay cau, Koles va Ailen khac thuong, neu giup ta xu ly rac roi tren dao, ta se can nhac.",
(2,25): "Ferok: Noi van de di. Voi nha tham hiem Ferok, deu la viec nho!",
(2,26): "Jiang: Cua bien co cua dot bien, moi de doa lon nhat. Nhieu dan dao bi hai. Den cua bien diet chung. Noi chuyen voi khinh khi cau de toi Map lon.",
(2,27): "Ferok: Toi di ngay.",
(2,28): "Jiang: Khoan. Khi ke lac loi tim lai ban than, ho de lai nhieu bai toan cho dung si. Ta xep thanh NV phu. Cau co the nhan o day; hoan thanh se co thuong tot.",
(2,29): "Jiang: Nho, NV co cap sao. Sao cang cao cang kho, nhung phan thuong cang lon!",
(2,30): "Ferok: Biet roi!",
(2,31): "Jiang: Dam cua dot bien dang ghet cuoi cung da bi day do. Cam on, dung si!",
(2,32): "Ferok: May viec nho nay qua de voi toi. Gio ong chap nhan yeu cau cua chung toi chu?",
(2,33): "Jiang: Khuc, khuc...",
(2,34): "Jiang: Dung si co tai. Gan day lai co rac roi lon hon, phai giai quyet som vi lien quan sinh mang moi nguoi tren dao.",
(2,35): "Ferok: A, noi nhanh viec gi?",
(2,36): "Jiang: Dao Dung Si gom nhieu dao. Phia bac la vung tuyet, giua la Dao Dem, duoi la Rung Ael va nui Zakun, deu nguy hiem. Nuoc gan day dang dang. Ta nghi tuyet phia bac tan chay. Can cau di dieu tra.",
(2,37): "Ferok: Bang son? Nghe vui day. Toi se toi vung tuyet ngay.",
(2,38): "Jiang: Vung tuyet o cuc bac Map. Noi voi khinh khi cau de toi Map lon.",
(2,39): "Ferok: Truong lang, xong roi. Bang Vuong van nam da thua duoi tay toi.",
(2,40): "Jiang: Khuc, ta nghi chua chac. Bang Vuong sao co the lam bang tan? Phai co nang luong dung nham manh nao do.",
(2,41): "Ferok: Suc dung nham? Y ong la Bang Vuong co dong bon?",
(2,42): "Jiang: Dung. Mot minh Bang Vuong kho lam bang ngan nam tan. Chac co quai vat lua manh khac giup no.",
(2,43): "Ferok: Dung roi. Truoc tran dau, no co noi ve suc dung nham va be ha Hasmani vi dai gi do.",
(2,44): "Jiang: Xem ra so menh da dinh, dieu phai den da den.",
(2,45): "Ferok: Truong lang, vay la sao?",
(2,46): "Jiang: Dao Dung Si tu xua thuoc Tay Quoc. Hasmani tham muon noi nay tu lau; to tien ta da danh lui chung nhieu lan.",
(2,47): "Jiang: Truyen rang Hasmani xay cung ngam do so duoi nui Zakun phia nam. Ke an minh ngan nam cuoi cung da lo dien.",
(2,48): "Ailen: Ferok, nguy roi, Jan mat tich.",
(2,49): "Ferok: A, co chuyen gi?",
(2,50): "Ailen: Hom qua hen di Rung Ael voi co ay. Co ay di truoc, nhung toi toi noi thi khong thay dau.",
(2,51): "Jiang: Viec nay co the lien quan Hasmani. Co ay la tieu thu Tay Quoc, tuc ke thu cua Hasmani, co the da bi bat lam con tin.",
(2,52): "Ferok: Vay phai lam sao?",
(2,53): "Jiang: Hay den Rung Ael xem tinh hinh. Co the co ay bi ket o do.",
(2,54): "Ferok: Toi se den Rung Ael.",
(2,55): "Jiang: Rung Ael o goc duoi phai Map lon da mo.",
(2,56): "Ferok: Truong lang, toi khong tim thay Jan o Rung Ael.",
(2,57): "Jiang: Dung si, cau da het suc. Ailen hinh nhu tim ra dau moi va da den Dao Dem o giua de xem.",
(2,58): "Ferok: Dao Dem? Nghe noi co ao linh. Sao Ailen co the di mot minh?",
(2,59): "Jiang: Dung vay. Ao linh bien hoa kho luong, mat thuong kho nhan ra. Ta can ma co ay van di.",
(2,60): "Ferok: Khong duoc, toi phai cuu co ay!",
(2,61): "Jiang: Muon toi Dao Dem, can vat nhin thau ao linh, goi la Thien Nhan. Co the ren o cho Kunsang. Du vat lieu thi noi voi tho ren de che tao.",
(2,62): "Ferok: Toi di tim vat lieu ren Thien Nhan!",
(2,63): "Jiang: Thien Nhan da xong. Mau toi Dao Dem xem tinh hinh!",
(2,64): "Jiang: Dao Dem o giua Map lon da mo!",
(2,65): "Ferok: Te roi, o Dao Dem toi khong thay Jan hay Ailen!",
(2,66): "Jiang: Xem ra ho that su bi be ha Hasmani bat roi.",
(2,67): "Ferok: Toi phai lam gi?",
(2,68): "Jiang: Mot trong hai tay sai dac luc cua Hasmani, Dia Nguc Vuong, dang dong day. Viec bang tan lan truoc la am muu cua no va Bang Vuong.",
(2,69): "Ferok: Toi se giet Dia Nguc Vuong.",
(2,70): "Jiang: Tre con, dung voi. Hap tap khong giai quyet duoc. Dia Nguc Vuong o sau long dat, nong khung khiep. Phai deo Khoa Bang moi an toan.",
(2,71): "Ferok: Lam sao co Khoa Bang?",
(2,72): "Jiang: Cau co the xem o cho tho ren Kunsang. Khi du vat lieu, ong ay se che tao cho cau.",
(2,73): "Jiang: Khoa Bang da xong, co the thach dau Dia Nguc Vuong. Vao tu phia duoi Map lon. (Goi y: nui Zakun da mo.)",
(2,74): "Ferok: Lan nay phai diet con cho khac cua be ha Hasmani.",
(2,75): "Jiang: NV hom nay deu o day.",
(2,76): "Vao Map lon, dung 2,4,6,8 de di chuyen.",
(2,77): "Jiang: Ben cang cho ke lac loi. Dao Dung Si se tiep tuc dung vung.",
(2,78): "Lang du: Nho mot dieu, dung si phai co da day!",
(2,79): "Phu thuy Ronin: Ta cung tung nhu cau.",
(3,0): "Heo rung: Hun... (tieng heo)",
(3,1): "Nguoi rung A: Nhin kia, co heo rung. Hom nay khong doi roi.",
(3,2): "B: Heo con, dung chay.",
(3,3): "Heo: Hun...hun",
(3,4): "Sau trong Rung Ael nang dep...",
(3,5): "Ferok: Qua Rung Ael la toi lau dai Hasmani.",
(3,6): "Ailen: Nhanh len. Koles sap khong tru noi; toi cam thay suc manh anh ay dang yeu di!",
(3,7): "Ferok: Ailen, em noi dung. Tien den lau dai Hasmani nao.",
(3,8): "Ailen: Khoan, Ferok. Toi cam thay nguy hiem o day. Nhin, nguoi rung! De toi diet chung.",
(3,9): "Ferok: Xem ra Ailen cua chung ta ngay cang manh.",
(3,10): "Ailen: Tat nhien. Ba huynh muoi ta nhat dinh hoan thanh su menh su phu giao.",
(3,11): "Ferok: Ta nen di nhanh. Troi sap toi, rung nay hay co heo rung.",
(4,0): "Ferok: Ailen, de toi xu ly quai o day, keo nguoi ta noi toi nhat gan.",
(4,1): "Ailen:...",
(4,2): "Ailen: Anh con nho cach chien dau chu?",
(4,3): "Ferok: Tat nhien. Dung coi thuong Ferok, du toi khong bang Koles.",
(4,4): "Ailen: Vay de xem dai anh hung cua ta quen bao nhieu.",
(4,5): "(Goi y: Vao huong dan, hay bam so tren man hinh!)",
(4,6): "Ferok: Dau tien, 2,4,6,8 de di cac huong.",
(4,7): "Ailen: Kha lam, khong lam mat mat su phu.",
(4,8): "Ferok: Con chieu manh hon. Muon thang dich, dung Skill rat can. 1,3,7,9 ung voi 4 Skill.",
(4,9): "Ailen: Skill manh hon don thuong. Dung thanh thao se tao combo cao hon.",
(4,10): "Ailen: Duoc roi, xem ra su phu lo thua. Ferok, ta chia duong toi lau dai Hasmani va chien dau cung Koles.",
(4,11): "Ferok: Uh, mong som toi lau dai Hasmani. Ta chia duong, hen gap o dong bang Kusman phia truoc.",
(4,12): "Ailen: Uh, toi di day!",
(4,13): "Ferok: Duoc, Ailen, can than nhe!",
(4,14): "(Goi y: Sau rung hay co heo rung. Hay ne cu huc cua chung.)",
(4,15): "(Goi y: Man choi thu khong chet!)",
(4,16): "Ailen: Kha lam, da biet di chuyen.",
(4,17): "Ferok: Ailen! Dung coi thuong toi. Sau nay toi se thanh dai anh hung.",
(4,18): "Ailen: Duoc, dai anh hung tuong lai. Buoc tiep theo la gi?",
(4,19): "Ferok: Tat nhien la tap danh thuong. Phim 5 de noi chuyen, OK va ATK thuong.",
(6,0): "Ferok: Phia truoc co nguoi nam. A, sao giong Ailen qua.",
(6,1): "Ferok: Ailen, em sao vay? (Nghi: Ailen se khong sao dau.)",
(6,2): "Ferok voi chay den ben Ailen. Thay co nam im tren dat, nuoc mat anh tuon roi...",
(6,3): "Ferok: Ailen, tinh lai di! Toi phai lam sao? Toi khong nen de em di mot minh, tat ca la loi cua toi. (Nuoc mat lam mat Ferok mo di.)",
(6,4): "Dung luc Ferok vo cung dau buon, Ailen dung day...",
(6,5): "Ailen: Nay, do ngoc, toi chua chet. Vua roi lua anh thoi, xem anh so chua kia.",
(6,6): "Ferok:...",
(6,7): "Ferok: Ailen, em lam toi so chet khiep. Toi tuong em gap nan. Toi con nghi Koles se giet toi, vi da hua bao ve em.",
(6,8): "Ailen: Ai can cac anh bao ve? Koles va anh deu la do ngoc.",
(6,9): "Ferok: Ailen, hua voi toi phai tu bao ve minh. Em la hoc tro ngoan cua su phu.",
(6,10): "Ailen: Yen tam, Ferok. Ta mau di tiep, nhat dinh hoan thanh NV su phu giao.",
(6,11): "Ferok: Uh.",
(6,12): "Ailen: Vay di nao.",
(8,0): "Ferok: Qua bai bien nay la dong bang Kusman. Toi phai nhanh de gap Koles.",
(9,0): "3 thg ago",
(9,1): "Ferok, Ailen va Koles gap co gai Jan gan dao Dung Si.",
(9,2): "Ho cung den dao Dung Si, mot hon dao la.",
(14,0): "Bang Vuong: Ta va nguoi khong thu han, sao den dat cua ta pha roi?",
(14,1): "Ferok: Nguoi de bang tan, hai cac dao cua Dung Si. Dung lai ngay, keo mat mang duoi luoi kiem ta.",
(14,2): "Bang Vuong: Ha ha, thu vi. Suc dung nham qua nhien co tac dung. Be ha Hasmani that than ky.",
(14,3): "Ferok: Noi nhieu vo ich. Chet di, quai vat.",
(14,4): "Bang Vuong: Vay nem suc bang van nam cua ta. Hon nguoi se dang cho chu nhan!",
(18,0): "Tuong ao linh: Kha lam, nhoc. Den duoc tan day.",
(18,1): "Ferok: Quai vat ao linh, anh ta va Jan dau?",
(18,2): "Tuong ao linh: Ha ha, con can hoi sao? Chac gio ho da quy duoi chan vua Hasmani. Chiu chet di, dung si dao Dung Si se chet o day!",
(18,3): "Ferok: Ta da nhin thau lop nguy trang ao linh. Con ban linh gi thi dem ra di!",
(18,4): "Tuong ao linh: De nguoi nem suc manh cua ta!",
(21,0): "Zakun hoi sinh, dat troi rung!",
(21,1): "Zakun: Ta bi giam duoi dat mot van nam. Lua gian nay se thanh suc manh cua ta!",
(21,2): "Zakun: No le dia nguc cua ta dau?",
(21,3): "Zakun: Thi hanh lenh chu nhan!",
(21,4): "Zakun: Dua con gian vo tan den vuc sau dia nguc!",
(21,5): "Luc do, Ferok va Ailen dang chien dau trong Rung Ael...",
(26,0): "Zakun: Ta bi giam mot van nam. Thu han nay se do len nguoi. No le vuc sau dia nguc, diet ke dich truoc mat!",
(26,1): "Zakun: Vay de ta tu tay xu nguoi, bang lua gian van nam!",
(26,2): "Dia Nguc Vuong hung manh da bi diet. Cho doi ban la tran cuoi voi Ma Vuong Hasmani. Den tho cua Hasmani rốt cuoc o dau?".replace('ốt','ot'),
(29,0): "Ferok: Phia truoc hinh nhu la Jan. Lai xem nao.",
(29,1): "Ferok: Jan, co sao khong?",
(29,2): "Jan: Bao boi cua ta, lai gan day.",
(29,3): "Ferok: Ai day? Khong phai Jan.",
(29,4): "Ferok: Con nguoi la ai? (Nghi: Sao co hai Jan, chang le ao giac?)",
(29,5): "Ferok: Jan, cuoc cung co o dau?",
(29,6): "Ferok: Khong tim thay Jan. Ve thanh hoi lao gia truoc.",
}

with SRC.open('r', encoding='utf-8-sig', newline='') as f:
    rows = list(csv.DictReader(f))
missing=[]
for r in rows:
    key=(int(r['section']), int(r['index']))
    if key not in T:
        missing.append(key)
    else:
        r['translated']=T[key]
if missing:
    raise SystemExit(f'Missing translations: {missing}')
OUT.parent.mkdir(parents=True, exist_ok=True)
with OUT.open('w', encoding='utf-8-sig', newline='') as f:
    w=csv.DictWriter(f, fieldnames=rows[0].keys())
    w.writeheader(); w.writerows(rows)
print('Wrote', OUT, 'rows', len(rows))